title: Designbysoil
email: designbysoil@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio of Abdul Rehman Khawar
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: designbysoil
github_username:  designbysoil

# Build settings
markdown: kramdown

# Timezone
timezone: America/Vancouver

plugins:
  - jekyll-seo-tag

# Server Config options
livereload: true    # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port